---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - application.laf.dev
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.laf.dev
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - application.laf.dev
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.laf.dev
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.laf.dev
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - database.laf.dev
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.laf.dev
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - instance.laf.dev
  resources:
  - instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instance.laf.dev
  resources:
  - instances/finalizers
  verbs:
  - update
- apiGroups:
  - instance.laf.dev
  resources:
  - instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oss.laf.dev
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - oss.laf.dev
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
