---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - database.laf.dev
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.laf.dev
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - database.laf.dev
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - database.laf.dev
  resources:
  - stores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.laf.dev
  resources:
  - stores/finalizers
  verbs:
  - update
- apiGroups:
  - database.laf.dev
  resources:
  - stores/status
  verbs:
  - get
  - patch
  - update
